# Generated by Django 5.0.1 on 2024-02-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user_type', models.CharField(choices=[('provider', 'Service Provider'), ('consumer', 'Service Consumer')], max_length=20)),
                ('profile_image', models.ImageField(blank=True, upload_to='profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='consumer_profile', serialize=False, to='authentication.user')),
                ('full_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='consumer_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='provider_profile', serialize=False, to='authentication.user')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('id_photograph', models.ImageField(upload_to='provider_id_photos/')),
                ('self_photograph', models.ImageField(upload_to='provider_self_photos/')),
                ('service_type', models.CharField(max_length=20)),
            ],
        ),
    ]
